# --- !Ups
insert into users (first_name, last_name, email) values ('Cristine', 'Strivens', 'cstrivens0@ibm.com');
insert into users (first_name, last_name, email) values (null, 'Boaler', 'lboaler1@qq.com');
insert into users (first_name, last_name, email) values ('Adina', null, 'astarrs2@goo.gl');
insert into users (first_name, last_name, email) values (null, 'Chesswas', 'cchesswas3@360.cn');
insert into users (first_name, last_name, email) values ('Benedict', 'Kenworthey', 'bkenworthey4@barnesandnoble.com');
insert into users (first_name, last_name, email) values ('Isaak', 'Lawleff', 'ilawleff5@qq.com');
insert into users (first_name, last_name, email) values (null, 'Rushsorth', 'lrushsorth6@utexas.edu');
insert into users (first_name, last_name, email) values ('Faydra', null, 'fmatticci7@virginia.edu');
insert into users (first_name, last_name, email) values ('Christy', null, 'chendrickx8@freewebs.com');
insert into users (first_name, last_name, email) values ('Kate', null, 'khappert9@wikispaces.com');
insert into users (first_name, last_name, email) values ('Rosene', 'Halladay', 'rhalladaya@bloglines.com');
insert into users (first_name, last_name, email) values (null, 'Ingledow', 'cingledowb@vimeo.com');
insert into users (first_name, last_name, email) values ('Valentina', 'Spolton', 'vspoltonc@biblegateway.com');
insert into users (first_name, last_name, email) values ('Gregoire', 'Graundisson', 'ggraundissond@netvibes.com');
insert into users (first_name, last_name, email) values (null, 'Allitt', 'vallitte@amazon.co.uk');
insert into users (first_name, last_name, email) values ('Deb', null, 'dcrudenf@hao123.com');
insert into users (first_name, last_name, email) values ('Antoni', 'Murdoch', 'amurdochg@biblegateway.com');
insert into users (first_name, last_name, email) values ('Moss', null, 'mjinkinsonh@ning.com');
insert into users (first_name, last_name, email) values ('Reyna', 'Garber', 'rgarberi@tuttocitta.it');
insert into users (first_name, last_name, email) values ('Bridie', 'Spanswick', 'bspanswickj@mapquest.com');


INSERT INTO forum_groups (name) VALUES ('Business Discussion');
INSERT INTO forum_groups (name) VALUES ('Scientific Discussions');
INSERT INTO forum_groups (name) VALUES ('Admin Announcement');
insert into forum_groups (name) values ('General Discussions');


insert into forums (name, group_id) values ('Automobile products', 1);
insert into forums (name, group_id) values ('Stocks', 1);


insert into forums (name, group_id) values ('Plants', 2);

insert into forums (name, group_id) values ('General Announcements', 3);
insert into forums (name, group_id) values ('Maintenance', 3);

insert into forums (name, group_id) values ('Memes', 4);
insert into forums (name, group_id) values ('Wacky Random', 4);

insert into threads (forum, name, created_by) values (1, 'BMW Cars', 1);
insert into threads (forum, name, created_by) values (1, 'Tesla Cars', 2);
insert into threads (forum, name, created_by) values (1, 'Toyota Prius', 2);
insert into threads (forum, name, created_by) values (2, 'Microsoft Corporation', 1);
insert into threads (forum, name, created_by) values (2, 'Apple Corporation', 1);
insert into threads (forum, name, created_by) values (2, 'Tesla Corporation', 1);
insert into threads (forum, name, created_by) values (3, 'Wolfsbane', 2);
insert into threads (forum, name, created_by) values (3, 'Buckthorn', 3);
insert into threads (forum, name, created_by) values (3, 'Mistletoe', 3);
insert into threads (forum, name, created_by) values (4, 'New Features', 4);
insert into threads (forum, name, created_by) values (4, 'Featured Ideas', 2);
insert into threads (forum, name, created_by) values (5, 'Maintenance Status', 3);
insert into threads (forum, name, created_by) values (6, 'Dogo', 1);
insert into threads (forum, name, created_by) values (6, 'Rare Pepes', 1);
insert into threads (forum, name, created_by) values (7, 'People Slipping', 3);
insert into threads (forum, name, created_by) values (7, 'Plane Landing Fails', 5);


insert into posts (thread_id, created_by, content) values (9, 16, 'blandit nam nulla integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem');
insert into posts (thread_id, created_by, content) values (4, 4, 'rutrum nulla nunc purus phasellus in felis donec semper sapien a libero');
insert into posts (thread_id, created_by, content) values (5, 10, 'non interdum in ante vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae duis');
insert into posts (thread_id, created_by, content) values (1, 11, 'dolor morbi vel lectus in quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus id turpis');
insert into posts (thread_id, created_by, content) values (10, 17, 'arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque');
insert into posts (thread_id, created_by, content) values (15, 12, 'phasellus sit amet erat nulla tempus vivamus in felis eu sapien cursus vestibulum proin eu');
insert into posts (thread_id, created_by, content) values (3, 16, 'cras pellentesque volutpat dui maecenas tristique est et tempus semper');
insert into posts (thread_id, created_by, content) values (9, 6, 'erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer ac neque duis');
insert into posts (thread_id, created_by, content) values (9, 14, 'turpis a pede posuere nonummy integer non velit donec diam neque vestibulum eget vulputate ut ultrices vel');
insert into posts (thread_id, created_by, content) values (7, 15, 'tristique est et tempus semper est quam pharetra magna ac consequat metus sapien ut nunc vestibulum ante');
insert into posts (thread_id, created_by, content) values (7, 9, 'turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh');
insert into posts (thread_id, created_by, content) values (5, 9, 'eleifend luctus ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum');
insert into posts (thread_id, created_by, content) values (5, 9, 'sodales sed tincidunt eu felis fusce posuere felis sed lacus morbi sem mauris laoreet ut rhoncus');
insert into posts (thread_id, created_by, content) values (3, 7, 'purus sit amet nulla quisque arcu libero rutrum ac lobortis');
insert into posts (thread_id, created_by, content) values (14, 13, 'molestie nibh in lectus pellentesque at nulla suspendisse potenti cras in purus eu magna vulputate luctus');
insert into posts (thread_id, created_by, content) values (7, 17, 'est congue elementum in hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam erat');
insert into posts (thread_id, created_by, content) values (7, 14, 'phasellus in felis donec semper sapien a libero nam dui proin leo odio porttitor id consequat in consequat ut nulla');
insert into posts (thread_id, created_by, content) values (8, 12, 'habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum');
insert into posts (thread_id, created_by, content) values (6, 9, 'consequat morbi a ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus');
insert into posts (thread_id, created_by, content) values (7, 7, 'proin interdum mauris non ligula pellentesque ultrices phasellus id sapien in');
insert into posts (thread_id, created_by, content) values (3, 1, 'amet nulla quisque arcu libero rutrum ac lobortis vel dapibus at diam nam tristique tortor eu pede');
insert into posts (thread_id, created_by, content) values (14, 13, 'mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus');
insert into posts (thread_id, created_by, content) values (4, 19, 'ut ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere');
insert into posts (thread_id, created_by, content) values (8, 11, 'dui luctus rutrum nulla tellus in sagittis dui vel nisl duis ac nibh fusce lacus purus aliquet at');
insert into posts (thread_id, created_by, content) values (8, 1, 'cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum');
insert into posts (thread_id, created_by, content) values (15, 17, 'in lacus curabitur at ipsum ac tellus semper interdum mauris ullamcorper purus sit amet nulla');
insert into posts (thread_id, created_by, content) values (9, 16, 'aenean auctor gravida sem praesent id massa id nisl venenatis lacinia aenean sit amet justo morbi ut odio cras mi');
insert into posts (thread_id, created_by, content) values (1, 17, 'sed sagittis nam congue risus semper porta volutpat quam pede lobortis ligula sit amet eleifend pede libero quis orci nullam');
insert into posts (thread_id, created_by, content) values (11, 18, 'id mauris vulputate elementum nullam varius nulla facilisi cras non');
insert into posts (thread_id, created_by, content) values (13, 9, 'in est risus auctor sed tristique in tempus sit amet sem fusce consequat nulla nisl nunc nisl duis bibendum felis');
insert into posts (thread_id, created_by, content) values (13, 11, 'adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis orci eget orci vehicula condimentum');
insert into posts (thread_id, created_by, content) values (5, 1, 'interdum mauris non ligula pellentesque ultrices phasellus id sapien in sapien iaculis congue vivamus metus arcu');
insert into posts (thread_id, created_by, content) values (4, 6, 'tempus vivamus in felis eu sapien cursus vestibulum proin eu mi nulla ac enim in tempor turpis nec euismod scelerisque');
insert into posts (thread_id, created_by, content) values (4, 5, 'velit eu est congue elementum in hac habitasse platea dictumst morbi vestibulum velit id');
insert into posts (thread_id, created_by, content) values (13, 6, 'ac est lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet sapien urna pretium nisl');
insert into posts (thread_id, created_by, content) values (14, 9, 'consequat in consequat ut nulla sed accumsan felis ut at dolor quis odio consequat varius integer ac leo');
insert into posts (thread_id, created_by, content) values (8, 9, 'habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla ut erat id mauris vulputate elementum nullam');
insert into posts (thread_id, created_by, content) values (6, 3, 'lectus aliquam sit amet diam in magna bibendum imperdiet nullam orci pede venenatis non sodales sed tincidunt eu felis fusce');
insert into posts (thread_id, created_by, content) values (1, 16, 'bibendum felis sed interdum venenatis turpis enim blandit mi in porttitor pede justo eu massa donec dapibus duis at velit');
insert into posts (thread_id, created_by, content) values (5, 11, 'curabitur convallis duis consequat dui nec nisi volutpat eleifend donec ut dolor morbi vel');
insert into posts (thread_id, created_by, content) values (10, 9, 'ut mauris eget massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque id justo sit');
insert into posts (thread_id, created_by, content) values (15, 17, 'augue quam sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt');
insert into posts (thread_id, created_by, content) values (14, 17, 'vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc');
insert into posts (thread_id, created_by, content) values (13, 19, 'neque libero convallis eget eleifend luctus ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante');
insert into posts (thread_id, created_by, content) values (5, 16, 'quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus');
insert into posts (thread_id, created_by, content) values (3, 18, 'in purus eu magna vulputate luctus cum sociis natoque penatibus');
insert into posts (thread_id, created_by, content) values (3, 13, 'eu est congue elementum in hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo');
insert into posts (thread_id, created_by, content) values (15, 10, 'sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum');
insert into posts (thread_id, created_by, content) values (6, 4, 'volutpat eleifend donec ut dolor morbi vel lectus in quam fringilla');
insert into posts (thread_id, created_by, content) values (15, 4, 'metus sapien ut nunc vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere');
insert into posts (thread_id, created_by, content) values (8, 11, 'mattis egestas metus aenean fermentum donec ut mauris eget massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies');
insert into posts (thread_id, created_by, content) values (5, 7, 'quis turpis sed ante vivamus tortor duis mattis egestas metus aenean fermentum donec ut mauris eget massa');
insert into posts (thread_id, created_by, content) values (4, 19, 'sed tincidunt eu felis fusce posuere felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl');
insert into posts (thread_id, created_by, content) values (4, 16, 'turpis enim blandit mi in porttitor pede justo eu massa donec dapibus duis at velit eu est congue');
insert into posts (thread_id, created_by, content) values (8, 1, 'quis libero nullam sit amet turpis elementum ligula vehicula consequat morbi a ipsum integer a nibh in');
insert into posts (thread_id, created_by, content) values (4, 7, 'nam dui proin leo odio porttitor id consequat in consequat ut');
insert into posts (thread_id, created_by, content) values (4, 7, 'amet justo morbi ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim');
insert into posts (thread_id, created_by, content) values (14, 4, 'vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus etiam');
insert into posts (thread_id, created_by, content) values (12, 11, 'pretium iaculis justo in hac habitasse platea dictumst etiam faucibus cursus urna ut');
insert into posts (thread_id, created_by, content) values (6, 14, 'gravida nisi at nibh in hac habitasse platea dictumst aliquam augue quam');
insert into posts (thread_id, created_by, content) values (12, 1, 'dui proin leo odio porttitor id consequat in consequat ut nulla sed accumsan felis ut at dolor quis odio');
insert into posts (thread_id, created_by, content) values (12, 9, 'donec posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet');
insert into posts (thread_id, created_by, content) values (14, 19, 'odio cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor sit amet');
insert into posts (thread_id, created_by, content) values (1, 15, 'ut nunc vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia');
insert into posts (thread_id, created_by, content) values (2, 15, 'in eleifend quam a odio in hac habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis');
insert into posts (thread_id, created_by, content) values (14, 3, 'ut nulla sed accumsan felis ut at dolor quis odio consequat varius integer ac');
insert into posts (thread_id, created_by, content) values (6, 9, 'congue eget semper rutrum nulla nunc purus phasellus in felis donec');
insert into posts (thread_id, created_by, content) values (9, 16, 'platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum neque sapien');
insert into posts (thread_id, created_by, content) values (13, 20, 'quam sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum praesent blandit');
insert into posts (thread_id, created_by, content) values (12, 3, 'in tempor turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec');
insert into posts (thread_id, created_by, content) values (1, 3, 'nulla integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus');
insert into posts (thread_id, created_by, content) values (5, 6, 'rutrum nulla tellus in sagittis dui vel nisl duis ac nibh fusce lacus purus aliquet at');
insert into posts (thread_id, created_by, content) values (7, 8, 'nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue a suscipit nulla elit');
insert into posts (thread_id, created_by, content) values (15, 9, 'sem praesent id massa id nisl venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede malesuada');
insert into posts (thread_id, created_by, content) values (9, 9, 'ac neque duis bibendum morbi non quam nec dui luctus');
insert into posts (thread_id, created_by, content) values (10, 5, 'pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim');
insert into posts (thread_id, created_by, content) values (14, 6, 'nisl venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo');
insert into posts (thread_id, created_by, content) values (13, 12, 'curae mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus at turpis donec posuere metus');
insert into posts (thread_id, created_by, content) values (15, 8, 'nunc donec quis orci eget orci vehicula condimentum curabitur in libero ut massa volutpat');
insert into posts (thread_id, created_by, content) values (1, 14, 'integer ac neque duis bibendum morbi non quam nec dui luctus');
insert into posts (thread_id, created_by, content) values (13, 6, 'dapibus nulla suscipit ligula in lacus curabitur at ipsum ac tellus semper interdum mauris ullamcorper purus sit amet nulla');
insert into posts (thread_id, created_by, content) values (4, 16, 'donec vitae nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue a suscipit nulla elit ac');
insert into posts (thread_id, created_by, content) values (16, 9, 'nunc commodo placerat praesent blandit nam nulla integer pede justo lacinia eget');
insert into posts (thread_id, created_by, content) values (9, 15, 'amet diam in magna bibendum imperdiet nullam orci pede venenatis non sodales sed tincidunt eu felis');
insert into posts (thread_id, created_by, content) values (2, 20, 'purus aliquet at feugiat non pretium quis lectus suspendisse potenti in eleifend');
insert into posts (thread_id, created_by, content) values (11, 17, 'cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis');
insert into posts (thread_id, created_by, content) values (11, 15, 'in eleifend quam a odio in hac habitasse platea dictumst maecenas ut massa quis augue');
insert into posts (thread_id, created_by, content) values (5, 5, 'ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi');
insert into posts (thread_id, created_by, content) values (2, 12, 'duis faucibus accumsan odio curabitur convallis duis consequat dui nec nisi volutpat eleifend donec ut dolor');
insert into posts (thread_id, created_by, content) values (8, 7, 'vehicula condimentum curabitur in libero ut massa volutpat convallis morbi odio odio elementum eu interdum');
insert into posts (thread_id, created_by, content) values (2, 6, 'donec dapibus duis at velit eu est congue elementum in hac habitasse platea dictumst morbi vestibulum velit');
insert into posts (thread_id, created_by, content) values (15, 15, 'vestibulum sit amet cursus id turpis integer aliquet massa id lobortis convallis tortor risus dapibus');
insert into posts (thread_id, created_by, content) values (8, 15, 'ultrices libero non mattis pulvinar nulla pede ullamcorper augue a suscipit');
insert into posts (thread_id, created_by, content) values (16, 1, 'gravida sem praesent id massa id nisl venenatis lacinia aenean sit amet justo morbi ut odio cras');
insert into posts (thread_id, created_by, content) values (8, 11, 'sem duis aliquam convallis nunc proin at turpis a pede posuere nonummy integer non velit donec diam neque vestibulum eget');
insert into posts (thread_id, created_by, content) values (9, 16, 'platea dictumst etiam faucibus cursus urna ut tellus nulla ut erat id mauris vulputate');
insert into posts (thread_id, created_by, content) values (11, 5, 'sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam erat volutpat');
insert into posts (thread_id, created_by, content) values (8, 17, 'turpis adipiscing lorem vitae mattis nibh ligula nec sem duis aliquam convallis nunc proin at');
insert into posts (thread_id, created_by, content) values (8, 5, 'curabitur gravida nisi at nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin');
insert into posts (thread_id, created_by, content) values (15, 6, 'consequat dui nec nisi volutpat eleifend donec ut dolor morbi vel lectus in quam fringilla rhoncus');


insert into posts (thread_id, created_by, replying_to, content) values (14, 8, 76, 'nisl duis ac nibh fusce lacus purus aliquet at feugiat non pretium quis lectus suspendisse potenti in eleifend quam a');
insert into posts (thread_id, created_by, replying_to, content) values (11, 3, 42, 'blandit non interdum in ante vestibulum ante ipsum primis in faucibus orci');
insert into posts (thread_id, created_by, replying_to, content) values (11, 17, 57, 'vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus etiam vel augue');
insert into posts (thread_id, created_by, replying_to, content) values (16, 8, 14, 'vestibulum proin eu mi nulla ac enim in tempor turpis nec euismod scelerisque quam turpis');
insert into posts (thread_id, created_by, replying_to, content) values (8, 6, 74, 'at turpis donec posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit');
insert into posts (thread_id, created_by, replying_to, content) values (9, 4, 69, 'suspendisse potenti nullam porttitor lacus at turpis donec posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit');
insert into posts (thread_id, created_by, replying_to, content) values (14, 2, 77, 'nulla pede ullamcorper augue a suscipit nulla elit ac nulla sed vel enim sit amet nunc viverra dapibus nulla suscipit');
insert into posts (thread_id, created_by, replying_to, content) values (13, 20, 94, 'diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam erat volutpat');
insert into posts (thread_id, created_by, replying_to, content) values (6, 16, 62, 'ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat');
insert into posts (thread_id, created_by, replying_to, content) values (6, 19, 69, 'commodo placerat praesent blandit nam nulla integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id');
insert into posts (thread_id, created_by, replying_to, content) values (12, 2, 53, 'mauris vulputate elementum nullam varius nulla facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus at');
insert into posts (thread_id, created_by, replying_to, content) values (11, 6, 91, 'donec dapibus duis at velit eu est congue elementum in hac habitasse platea dictumst morbi vestibulum velit id');
insert into posts (thread_id, created_by, replying_to, content) values (2, 6, 78, 'eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus in felis eu sapien cursus');
insert into posts (thread_id, created_by, replying_to, content) values (9, 20, 8, 'faucibus cursus urna ut tellus nulla ut erat id mauris vulputate elementum nullam varius nulla facilisi cras non');
insert into posts (thread_id, created_by, replying_to, content) values (5, 20, 35, 'eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus');

